# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eduard/programming/EvolutionaryCreator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eduard/programming/EvolutionaryCreator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eduard/programming/EvolutionaryCreator/CMakeFiles /home/eduard/programming/EvolutionaryCreator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eduard/programming/EvolutionaryCreator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named Evolutionary

# Build rule for target.
Evolutionary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Evolutionary
.PHONY : Evolutionary

# fast build rule for target.
Evolutionary/fast:
	$(MAKE) -f dependencies/Evolutionary/src/CMakeFiles/Evolutionary.dir/build.make dependencies/Evolutionary/src/CMakeFiles/Evolutionary.dir/build
.PHONY : Evolutionary/fast

#=============================================================================
# Target rules for targets named EvolutionaryCreator

# Build rule for target.
EvolutionaryCreator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EvolutionaryCreator
.PHONY : EvolutionaryCreator

# fast build rule for target.
EvolutionaryCreator/fast:
	$(MAKE) -f src/CMakeFiles/EvolutionaryCreator.dir/build.make src/CMakeFiles/EvolutionaryCreator.dir/build
.PHONY : EvolutionaryCreator/fast

#=============================================================================
# Target rules for targets named OpenGLContext

# Build rule for target.
OpenGLContext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenGLContext
.PHONY : OpenGLContext

# fast build rule for target.
OpenGLContext/fast:
	$(MAKE) -f src/CMakeFiles/OpenGLContext.dir/build.make src/CMakeFiles/OpenGLContext.dir/build
.PHONY : OpenGLContext/fast

dependencies/imgui/imgui.o: dependencies/imgui/imgui.cpp.o

.PHONY : dependencies/imgui/imgui.o

# target to build an object file
dependencies/imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/dependencies/imgui/imgui.cpp.o
.PHONY : dependencies/imgui/imgui.cpp.o

dependencies/imgui/imgui.i: dependencies/imgui/imgui.cpp.i

.PHONY : dependencies/imgui/imgui.i

# target to preprocess a source file
dependencies/imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/dependencies/imgui/imgui.cpp.i
.PHONY : dependencies/imgui/imgui.cpp.i

dependencies/imgui/imgui.s: dependencies/imgui/imgui.cpp.s

.PHONY : dependencies/imgui/imgui.s

# target to generate assembly for a file
dependencies/imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/dependencies/imgui/imgui.cpp.s
.PHONY : dependencies/imgui/imgui.cpp.s

dependencies/imgui/imgui_demo.o: dependencies/imgui/imgui_demo.cpp.o

.PHONY : dependencies/imgui/imgui_demo.o

# target to build an object file
dependencies/imgui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/dependencies/imgui/imgui_demo.cpp.o
.PHONY : dependencies/imgui/imgui_demo.cpp.o

dependencies/imgui/imgui_demo.i: dependencies/imgui/imgui_demo.cpp.i

.PHONY : dependencies/imgui/imgui_demo.i

# target to preprocess a source file
dependencies/imgui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/dependencies/imgui/imgui_demo.cpp.i
.PHONY : dependencies/imgui/imgui_demo.cpp.i

dependencies/imgui/imgui_demo.s: dependencies/imgui/imgui_demo.cpp.s

.PHONY : dependencies/imgui/imgui_demo.s

# target to generate assembly for a file
dependencies/imgui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/dependencies/imgui/imgui_demo.cpp.s
.PHONY : dependencies/imgui/imgui_demo.cpp.s

dependencies/imgui/imgui_draw.o: dependencies/imgui/imgui_draw.cpp.o

.PHONY : dependencies/imgui/imgui_draw.o

# target to build an object file
dependencies/imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/dependencies/imgui/imgui_draw.cpp.o
.PHONY : dependencies/imgui/imgui_draw.cpp.o

dependencies/imgui/imgui_draw.i: dependencies/imgui/imgui_draw.cpp.i

.PHONY : dependencies/imgui/imgui_draw.i

# target to preprocess a source file
dependencies/imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/dependencies/imgui/imgui_draw.cpp.i
.PHONY : dependencies/imgui/imgui_draw.cpp.i

dependencies/imgui/imgui_draw.s: dependencies/imgui/imgui_draw.cpp.s

.PHONY : dependencies/imgui/imgui_draw.s

# target to generate assembly for a file
dependencies/imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/dependencies/imgui/imgui_draw.cpp.s
.PHONY : dependencies/imgui/imgui_draw.cpp.s

src/ui/ImGuiGlfw.o: src/ui/ImGuiGlfw.cpp.o

.PHONY : src/ui/ImGuiGlfw.o

# target to build an object file
src/ui/ImGuiGlfw.cpp.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/ui/ImGuiGlfw.cpp.o
.PHONY : src/ui/ImGuiGlfw.cpp.o

src/ui/ImGuiGlfw.i: src/ui/ImGuiGlfw.cpp.i

.PHONY : src/ui/ImGuiGlfw.i

# target to preprocess a source file
src/ui/ImGuiGlfw.cpp.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/ui/ImGuiGlfw.cpp.i
.PHONY : src/ui/ImGuiGlfw.cpp.i

src/ui/ImGuiGlfw.s: src/ui/ImGuiGlfw.cpp.s

.PHONY : src/ui/ImGuiGlfw.s

# target to generate assembly for a file
src/ui/ImGuiGlfw.cpp.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/ui/ImGuiGlfw.cpp.s
.PHONY : src/ui/ImGuiGlfw.cpp.s

src/ui/ImGuiOpengl.o: src/ui/ImGuiOpengl.cpp.o

.PHONY : src/ui/ImGuiOpengl.o

# target to build an object file
src/ui/ImGuiOpengl.cpp.o:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/ui/ImGuiOpengl.cpp.o
.PHONY : src/ui/ImGuiOpengl.cpp.o

src/ui/ImGuiOpengl.i: src/ui/ImGuiOpengl.cpp.i

.PHONY : src/ui/ImGuiOpengl.i

# target to preprocess a source file
src/ui/ImGuiOpengl.cpp.i:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/ui/ImGuiOpengl.cpp.i
.PHONY : src/ui/ImGuiOpengl.cpp.i

src/ui/ImGuiOpengl.s: src/ui/ImGuiOpengl.cpp.s

.PHONY : src/ui/ImGuiOpengl.s

# target to generate assembly for a file
src/ui/ImGuiOpengl.cpp.s:
	$(MAKE) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/ui/ImGuiOpengl.cpp.s
.PHONY : src/ui/ImGuiOpengl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... imgui"
	@echo "... edit_cache"
	@echo "... Evolutionary"
	@echo "... EvolutionaryCreator"
	@echo "... OpenGLContext"
	@echo "... dependencies/imgui/imgui.o"
	@echo "... dependencies/imgui/imgui.i"
	@echo "... dependencies/imgui/imgui.s"
	@echo "... dependencies/imgui/imgui_demo.o"
	@echo "... dependencies/imgui/imgui_demo.i"
	@echo "... dependencies/imgui/imgui_demo.s"
	@echo "... dependencies/imgui/imgui_draw.o"
	@echo "... dependencies/imgui/imgui_draw.i"
	@echo "... dependencies/imgui/imgui_draw.s"
	@echo "... src/ui/ImGuiGlfw.o"
	@echo "... src/ui/ImGuiGlfw.i"
	@echo "... src/ui/ImGuiGlfw.s"
	@echo "... src/ui/ImGuiOpengl.o"
	@echo "... src/ui/ImGuiOpengl.i"
	@echo "... src/ui/ImGuiOpengl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

